name: StyleCI
on: [push, pull_request]
jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: analyze code with StyleCI
      uses: nathane/styleci-action@latest # Available tags: "@1.1", "@v1.1.0"
      with:
        styleci_api_key: ${{ secrets.STYLECI_API_KEY }} # required
        options: '--no-interaction --dry-run'
        directory: './community-themes/'
